# Book settings
# Learn more at https://jupyterbook.org/customize/config.html

title: Gender Pay Gap
author: InfoVis Group J3
copyright: "2023"
logo: static/images/logo.jpg
html:
  favicon: static/images/favicon.ico
  use_repository_button: true

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Information about where the book exists on the web
repository:
  url: https://github.com/p-adema/info-vis
  branch: main  # Which branch of the repository should be used when creating links (optional)

sphinx:
  extra_extensions:
    # This is to work around the bug of no syntax highlighting
    - "IPython.sphinxext.ipython_console_highlighting"
  config:
    html_context:
      default_mode: 'light'
    html_static_path: 'static'
    html_css_files:
      - css/notebook.css
    html_js_files:
      - js/enforce-light-theme.js

      # This is for plotly to work
      - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js
